name: 博客打包部署

on:
  workflow_dispatch:
  # push:
  #   branches: [main] # 当推送到main分支时触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build project
        run: bun run build # 假设您的 package.json 中有 build 脚本

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/useradmin/nginx/html
            git pull origin main
            bun install
            bun run build

          # pm2 restart your-app  # 如果使用pm2管理Node.js应用
