name: Deploy to server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build project
        run: bun run build

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            if [ ! -d "/home/useradmin/nginx/weboke/.git" ]; then
              git clone https://github.com/yourusername/yourrepository.git /home/useradmin/nginx/weboke
            fi
            cd /home/useradmin/nginx/weboke
            git pull origin main
            if ! command -v bun &> /dev/null; then
              echo "Bun is not installed. Installing Bun..."
              curl -fsSL https://bun.sh/install | bash
              export PATH="/root/.bun/bin:$PATH"
            fi
            bun install
            bun run build
